### ISSUE TITLE
undefined symbol: cuCtxGetDevice

### ISSUE THREAD

**Issue by mrocklin** [Akshay-Venkatesh/ucx-py#101]
When I build with the ref/ucx-cuda branch I have difficulty getting some of the dask-oriented ucx-py tests to run.

```
tests/test_dask_gpu_scatter.py (ucx-gpu) mrocklin@dgx15:~/ucx-py$ py.test tests/test_dask_* -s
======================================================================== test session starts ========================================================================
platform linux -- Python 3.7.3, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: /home/nfs/mrocklin/ucx-py
collected 2 items

tests/test_dask_gpu_scatter.py /home/nfs/mrocklin/miniconda/envs/ucx-gpu/bin/python: symbol lookup error: /home/nfs/mrocklin/miniconda/envs/ucx-gpu/lib/ucx/libuct_ib.so.0: undefined symbol: cuCtxGetDevice
```

I think that @rjzamora also ran into this.

**Comment by Akshay-Venkatesh** [comment]
Matt - this may be related to the errors you saw with being unable to find the path for `cuda.h` on the machine until you explicitly specified it in `C_INCLUDE. You may need to explicitly add paths in `LD_LIBRARY_PATH`.

**Comment by mrocklin** [comment]
I wrote this on another issue erroneously and meant to add it here.

This test fails

```
(ucx-dev) mrocklin@dgx15:~/ucx-py$ py.test tests/test_multiple_listeners.py  -s
============================================ test session starts =============================================
platform linux -- Python 3.7.3, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: /home/nfs/mrocklin/ucx-py
plugins: asyncio-0.10.0
collecting ... /home/nfs/mrocklin/miniconda/envs/ucx-dev/bin/python: symbol lookup error: /home/nfs/mrocklin/miniconda/envs/ucx-gpu/lib/ucx/libuct_ib.so.0: undefined symbol: cuCtxGetDevice
```

```python
import ucp
import asyncio

ucp.init()


async def hello(ep, listener):
    await asyncio.sleep(0)
    ep.close()
    ucp.stop_listener(listener)


def test_multiple_listeners():
    lf1 = ucp.start_listener(hello, is_coroutine=True)
    lf2 = ucp.start_listener(hello, is_coroutine=True)
    assert lf1.port > 0
    assert lf2.port > 0
    assert lf1.port != lf2.port

    lf1.coroutine.close()
    lf2.coroutine.close()
    ucp.stop_listener(lf1)
    ucp.stop_listener(lf2)
```

More generally, can you verify that tests pass for you?

**Comment by mrocklin** [comment]
> Matt - this may be related to the errors you saw with being unable to find the path for cuda.h on the machine until you explicitly specified it in C_INCLUDE. You may need to explicitly add paths in LD_LIBRARY_PATH.

I've been using [these docs](https://docs.google.com/document/d/1d7D5QNy4jFA7UYHjzxCrb1DrKUZ8g67UuVQF7cvi9rc/edit#) to setup.  If you're at all interested in trying this same process and providing feedback on how it could be improved that would be very welcome.  A few of us use this process, so if we can improve that doc I think that it would smooth things over considerably.

Also cc @rjzamora who probably has a better chance of finding the right paths to add to `LD_LIBRARY_PATH`

**Comment by Akshay-Venkatesh** [comment]
Hmm. I stand corrected. I'm seeing the issue with `ref/ucx-cuda` (even after rebasing with master).

```
akvenkatesh@prm-dgx-33:~/ucx-py$ py.test tests/test_multiple_listeners.py  -s
======================================================== test session starts ========================================================
platform linux -- Python 3.7.2, pytest-4.3.0, py-1.8.0, pluggy-0.9.0
rootdir: /home/akvenkatesh/ucx-py, inifile:
plugins: repeat-0.8.0, asyncio-0.10.0
collecting ... /home/akvenkatesh/py/install/bin/python3: symbol lookup error: /home/akvenkatesh/ucx-github/build/lib/ucx/libuct_ib.so.0: undefined symbol: cuCtxGetDevice
```
I'll update back when I've resolved this issue. I'm not sure why we see this problem yet.

**Comment by rjzamora** [comment]
BTW, pointing the `LD_LIBRARY_PATH` at `/usr/local/cuda-9.2/lib64` did not fix the problem for me.

**Comment by Akshay-Venkatesh** [comment]
@mrocklin @rjzamora 
Had some issues with rebase on `ref/ucx-cuda`. Can you please change to this branch https://github.com/Akshay-Venkatesh/ucx/tree/1ad5b17/ucx-cuda and retry? I'm able to run the tests without the symbol issue and have different patches on top of current ucx master.

Sorry about the hassle.

**Comment by rjzamora** [comment]
@mrocklin @Akshay-Venkatesh  `1ad5b17/ucx-cuda` fixes this error for me. Thanks!

**Comment by Akshay-Venkatesh** [comment]
Good to know. Will close for now.

**Comment by mrocklin** [comment]
I'm still having trouble building this 

```
./configure: line 17888: PKG_PROG_PKG_CONFIG: command not found
checking if ln -s supports --relative... yes
checking for dot... yes
checking for doxygen... /home/nfs/mrocklin/miniconda/envs/ucx-gpu/bin/doxygen
checking for perl... /home/nfs/mrocklin/miniconda/envs/ucx-gpu/bin/perl
checking for pdflatex... no
configure: WARNING: pdflatex not found - will not generate doxygen PDF documentation
checking for makeindex... no
checking for bibtex... no
checking for egrep... /bin/egrep
./configure: line 26873: syntax error near unexpected token `newline'
./configure: line 26873: `              PKG_CHECK_MODULES('
Makefile:587: recipe for target 'config.status' failed
make: *** [config.status] Error 2
(ucx-gpu) mrocklin@dgx15:~/ucx$
```

I also found that I needed to install a newer doxygen to get past other errors.

**Comment by mrocklin** [comment]
Sorry, that was probably a bad file.  Starting from a clean environment

```
(ucx-gpu) mrocklin@dgx15:~/ucx$ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config/m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'config/m4'.
libtoolize: copying file 'config/m4/libtool.m4'
libtoolize: copying file 'config/m4/ltoptions.m4'
libtoolize: copying file 'config/m4/ltsugar.m4'
libtoolize: copying file 'config/m4/ltversion.m4'
libtoolize: copying file 'config/m4/lt~obsolete.m4'
autoreconf: running: /home/nfs/mrocklin/miniconda/envs/ucx-gpu/bin/autoconf
configure.ac:33: error: possibly undefined macro: AS_IF
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:34: error: possibly undefined macro: AC_SUBST
configure.ac:137: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:237: error: possibly undefined macro: AC_DEFINE
configure:26956: error: possibly undefined macro: AC_MSG_WARN
autoreconf: /home/nfs/mrocklin/miniconda/envs/ucx-gpu/bin/autoconf failed with exit status: 1
```

**Comment by mrocklin** [comment]
@rjzamora pointed me to `conda install pkgconfig` which seems to solve the problem.  I've also updated the [setup doc](https://docs.google.com/document/d/1d7D5QNy4jFA7UYHjzxCrb1DrKUZ8g67UuVQF7cvi9rc/edit?usp=sharing) I've been working from

**Comment by jakirkham** [comment]
Just as an update here, what you probably want is `pkg-config` (the Unix build tool). The `pkgconfig` Python library (note absence of `-`) is for Python programs that want to use the Unix build tool from Python. Have submitted PR ( https://github.com/dask/dask-blog/pull/31 ) to update the blog as well.
