### ISSUE TITLE
Passing in tuple for lf argument?

### ISSUE THREAD

**Issue by mrocklin** [Akshay-Venkatesh/ucx-py#107]
I'm getting these errors (sorry for the lack of a proper traceback)

```python-traceback
AttributeError: 'tuple' object has no attribute 'is_coroutine'
Exception ignored in: 'ucp_py.accept_callback'
```

Context

```cython
cdef void accept_callback(void *client_ep_ptr, void *lf):
    client_ep = Endpoint()
    client_ep.ep = client_ep_ptr
    listener_instance = (<object> lf)
    if not listener_instance.is_coroutine:
        (listener_instance.cb)(client_ep, listener_instance)
    else:
        current_loop = asyncio.get_event_loop()
        current_loop.create_task((listener_instance.cb)(client_ep, listener_instance))
```

Any chance that the passed in `lf` value isn't what we think it is?

**Comment by Akshay-Venkatesh** [comment]
@mrocklin Can you share the preceding call to [`start_listener`](https://github.com/Akshay-Venkatesh/ucx-py/blob/devel/ucp/_libs/ucp_py.pyx#L608) which leads up to this? I suppose I should have an `assert` to make sure `lf` is `ListenerFuture` object.

**Comment by mrocklin** [comment]
It's here: https://github.com/dask/distributed/pull/2591/files#diff-ca5c24c584111a291f763107e4065539R286

(and yes, we are)

**Comment by Akshay-Venkatesh** [comment]
Should I assume that this issue occurs after the new retry logic has been added to `get_endpoint`? Want to isolate the commit that causes this. Would it be possible to check with this commit https://github.com/Akshay-Venkatesh/ucx-py/commit/21917c163c8a585126963cdd2985f40d3847f050?

**Comment by mrocklin** [comment]
When I try with that commit I can get the following error:

Exception ignored in: 'ucp_py.accept_callback'
AttributeError: 'Future' object has no attribute 'is_coroutine'

Note that I've also removed the `await` in front of my creation of my
endpoint.

**Comment by Akshay-Venkatesh** [comment]
Is this a new benchmark/test that we're trying? I don't recollect running into this specific error in the past.

**Comment by mrocklin** [comment]
I'm running the experiment in https://github.com/Akshay-Venkatesh/ucx-py/issues/106#issuecomment-494076119

**Comment by mrocklin** [comment]
I tried printing out the type and the object that I received and got very odd results.  Other objects that had nothing to do with Dask communications or UCX were present.  

I suspect that the `lf` object that is passed in is being garbage collected before the `accept_callback` function is being run, Python creates some new object that reuses the object ID, and we get this behavior.

**Comment by mrocklin** [comment]
Yes, if I choose to hold onto this object in an external list (effectively creating a leak) then the problem goes away.

```diff
diff --git a/ucp/_libs/ucp_py.pyx b/ucp/_libs/ucp_py.pyx
index e9ea2f7..3143126 100644
--- a/ucp/_libs/ucp_py.pyx
+++ b/ucp/_libs/ucp_py.pyx
@@ -604,6 +603,8 @@ def init():

     return rval

+listener_futures = []
+
 @ucp_logger
 def start_listener(py_func, listener_port = -1, is_coroutine = False):
     """Start listener to accept incoming connections
@@ -661,6 +662,7 @@ def start_listener(py_func, listener_port = -1, is_coroutine = False):
             s.close()
             port = addr[1]

+        listener_futures.append(lf)
         listener.listener_ptr = ucp_py_listen(accept_callback, <void *>lf, <int *> &port)
         if <void *> NULL != listener.listener_ptr:
             lf.listener = listener
```

**Comment by mrocklin** [comment]
(not that that's an ideal solution, but at least it isolates the problem)

**Comment by mrocklin** [comment]
cc @Akshay-Venkatesh

**Comment by Akshay-Venkatesh** [comment]
Decided to create a PR : https://github.com/Akshay-Venkatesh/ucx-py/pull/110

**Comment by Akshay-Venkatesh** [comment]
Closing for now
