### ISSUE TITLE
Sub-optimal internode performance for numpy transfers

### ISSUE THREAD

**Issue by Akshay-Venkatesh** [Akshay-Venkatesh/ucx-py#66]
@TomAugspurger 

The peak bandwidth on this system between two nodes is close to 12GB/s but I'm seeing less than that with the `recv-into-client.py` benchmark. Will try understand the cause and update here:

```
akvenkatesh@prm-dgx-22:~/ucx-py-tom$ python3 benchmarks/recv-into-client.py -o numpy --n-iter=100 -s 192.168.40.31 -p 13337
Roundtrip benchmark
-------------------
n_iter   | 100
n_bytes  | 10.00 MB
recv     | recv_into
object   | numpy

===================
5.22 GB / s
===================
```

**Comment by Akshay-Venkatesh** [comment]
Long resolved.

**Comment by mrocklin** [comment]
I may be raising this again.  I'm not seeing great performance with
recv_obj.  I'll start a new issue though with hopefully a simple example.

**Comment by Akshay-Venkatesh** [comment]
@mrocklin This issue was concerning `recv_into`. With `recv_obj` the allocation in the critical path is the primary cause for lower performance.
