### ISSUE TITLE
Drop `_py` from the library name?

### ISSUE THREAD

**Issue by mrocklin** [Akshay-Venkatesh/ucx-py#82]
It seems like it's common to import this library as ...

```python
import ucp_py as ucp
```

I wonder if, instead, we might just structure the Python library so that it is named `ucp` from within Python.  This repository would continue to be named `ucp-py`, but we would import it just as `ucp`.  This might be a bit more idiomatic from the Python side.

**Comment by Akshay-Venkatesh** [comment]
That would be fine, Matt. I don't have an issue with this.

**Comment by quasiben** [comment]
I'd be happy to make the changes necessary

**Comment by Akshay-Venkatesh** [comment]
@quasiben Please go ahead. Just a heads up that you would need to make changes in tests and benchmarks which make the above usage.
