### ISSUE TITLE
Poor performance on benchmarks/recv-into-client.py

### ISSUE THREAD

**Issue by mrocklin** [Akshay-Venkatesh/ucx-py#91]
After following the instructions on [this doc](https://docs.google.com/document/d/1d7D5QNy4jFA7UYHjzxCrb1DrKUZ8g67UuVQF7cvi9rc/edit?usp=sharing) both @rjzamora and I got sub-optimal performance on `benchmarks/recv-into-client.py`

### Expected

```
Roundtrip benchmark
-------------------
n_iter   | 10
n_bytes  | 10.00 MB
recv     | recv_into
object   | cupy
inc      | False

===================
7.86 GB / s
===================
```

### Observed

```
Roundtrip benchmark
-------------------
n_iter   | 10
n_bytes  | 10.00 MB
recv     | recv_into
object   | cupy
inc      | False

===================
645.45 MB / s
===================
```

Is there something we can do to diagnose this?

cc @Akshay-Venkatesh @pentschev

**Comment by mrocklin** [comment]
I at least am running this on NVIDIA's DGX-16 box.

**Comment by pentschev** [comment]
> I at least am running this on NVIDIA's DGX-16 box.

Could you try on DGX-15 as well, just in case? I'd like to eliminate the possibility of diverging software configurations between the two.

**Comment by mrocklin** [comment]
I'll try that out

**Comment by mrocklin** [comment]
Confirmed that things work well on dgx-15.  Do we know what the hardware difference is between those two machines?

**Comment by pentschev** [comment]
I suspect it's not a hardware difference, but rather software. I've heard it's still quite cumbersome to have everything working smoothly, we'll need to escalate this to ops.

That being said, I think this issue can be closed, since it's not an issue with ucx-py.

**Comment by mrocklin** [comment]
Lets keep it open for now if it's ok.  I think we're effectively using this issue tracker for general experience (or at least, I know of no better place).

For context, I didn't build anything differently.  I just used the same environment that was built on dgx-16 on dgx-15 (they are connected with NFS).

**Comment by pentschev** [comment]
> Lets keep it open for now if it's ok. I think we're effectively using this issue tracker for general experience (or at least, I know of no better place).

Fine by me.

> For context, I didn't build anything differently. I just used the same environment that was built on dgx-16 on dgx-15 (they are connected with NFS).

Yes, I've heard the same from @rjzamora, I think it's fair to rule out an issue with any of your environments. My suspicion is really that we have something misconfigured, but there may exist a physical connection problem, even though I would expect that to manifest in a different form (e.g., an error or missing networking interface).
