### ISSUE TITLE
Use Python naming conventions

### ISSUE THREAD

**Issue by mrocklin** [Akshay-Venkatesh/ucx-py#92]
For user-visible classes and methods, it might be useful to use Python conventions for names. A few themes to be aware of.

-  Camel casing for classes
-  Generally we don't namespace with underscores, c-style, but rely on namespaces or context 

So a couple of concrete recommendations

```diff
-cdef class ucp_py_ep:
+cdef class EndPoint:
```

```diff
-def destroy_ep(ucp_ep):
+def destroy_ep(ep):
     """Destroy an existing endpoint connection to a peer

     Parameters
     ----------
-    ucp_ep: ucp_py_ep
+    ep: EndPoint
```

I briefly tried making a few of these changes but ran into compile errors, I suspect due to mismatches in the C code (though to be honest, I didn't dive too deeply).

@Akshay-Venkatesh there is clearly some boundary between where C-style conventions should take precedence and where Python style conventions to take precedence.  Probably this boundary is somewhere in the Cython code, but I don't know exactly where.  Given that you do most of the actual development here I'd be happy to defer to your judgment.

Also cc'ing @rjzamora who might be interested in executing on a few of these changes.  I suspect that he's both comfortable with C and has a sense for Python conventions.

**Comment by rjzamora** [comment]
Sure - I can try to work in these style changes.  Any thoughts/suggestions from @Akshay-Venkatesh are welcome

**Comment by mrocklin** [comment]
You might also keep your eyes open for other situations where novice Python users might be somewhat confused by the interface.

**Comment by rjzamora** [comment]
I submitted PR#93 to address the class-naming component of this issue.  I made a few changes to the python source without needing to touch the pure C code.  The `EndPoint` name change does break dask compatibility, but the fix is simple.

**Comment by mrocklin** [comment]
This seems to be resolved.  Thanks @rjzamora
