### ISSUE TITLE
Performance of recv_obj vs recv_future

### ISSUE THREAD

**Issue by mrocklin** [Akshay-Venkatesh/ucx-py#95]
Currently in the Dask UCX Comm we send the lengths of all of the bytestrings ahead of time, and then use `ep.recv_obj(nbytes=)` for each frame.  Should we instead be using `ep.recv_future()` and trust UCX to handle sending the framing for us?  What are the performance implications of `recv_obj` vs `recv_future`?

**Comment by Akshay-Venkatesh** [comment]
Both `recv_future` and `recv_obj` result in memory being allocated in the critical path today. The difference as you may already know is that recv_future probes the network for an incoming message and allocates memory on _host_ appropriately. `recv_obj` allocates memory on _host_ / _device_ according to the hint passed. 

If the message size and type of the incoming transfer size is known ahead of time, it may be better to use `recv_obj`. Ideally, both don't have a memory allocation call in the critical path and we instead use a memory pool from which we sub-allocacte.

**Comment by mrocklin** [comment]
OK, that answers my question.  Thanks @Akshay-Venkatesh !
