### ISSUE TITLE
Destination is Unreachable causes segmentation fault

### ISSUE THREAD

**Issue by mrocklin** [Akshay-Venkatesh/ucx-py#97]
In running some of the Dask tests I come across this

```
(ucx-dev) mrocklin@dgx15:~/distributed$ py.test distributed/comm/tests/test_comms.py::test_ucx_client_server -s
========================================== test session starts ==========================================
platform linux -- Python 3.7.3, pytest-4.4.1, py-1.8.0, pluggy-0.9.0 -- /home/nfs/mrocklin/miniconda/envs/ucx-dev/bin/python
cachedir: .pytest_cache
rootdir: /home/nfs/mrocklin/distributed, inifile: setup.cfg
plugins: asyncio-0.10.0
collected 1 item

distributed/comm/tests/test_comms.py::test_ucx_client_server [1556549940.707934] [dgx15:16780:0]   rdmacm_iface.c:403  UCX  ERROR received event RDMA_CM_EVENT_UNREACHABLE. status = 1. Peer: 10.33.225.160:21895.
[1556549940.707968] [dgx15:16780:0]     ucp_worker.c:495  UCX  ERROR error 'Destination is unreachable' will not be handled for ep 0x7fbbc039d048 - /
unable to send UCX data message
[dgx15:16780:1:16780] Caught signal 11 (Segmentation fault: address not mapped to object at address 0xffffffffffffffb0)
```

Probably this is some configuration or mismatch on my end.  Ideally though for failures like these we would raise some informative Python exception rather than halt the program.

**Comment by Akshay-Venkatesh** [comment]
@mrocklin 3a71864 should address this. There is one case when notification that destination is unreachable arrives late in which case the error message is printed but no exception is raised (because we can't catch this at a reasonable place). I can still detect that but the best I can probably do there is to terminate the program. Will that work?

**Comment by mrocklin** [comment]
Ideally the program wouldn't terminate.  Having the program terminate is very odd for Python users, particularly when working interactively.  Instead, they typically see exceptions that tell them that things didn't work, and then they go ahead and try something else.

For example, a user might set up a bunch of work on their own, then decide to use Dask + UCX, get an error, and then decide to use Dask + TCP instead.  If we terminate things then they lose their previous work from this session.

**Comment by mrocklin** [comment]
This also occurs when workers start up before the scheduler.  They try to connect, fail, and terminate.  Ideally they would continue to try until some timeout was reached.

Often this occurs when people set up the whole system on a cluster.  It's hard to predict which components will come up first.

**Comment by Akshay-Venkatesh** [comment]
@mrocklin Having a retry mechanism makes sense and should be feasible. I'll open a PR to handle this.

**Comment by mrocklin** [comment]
Was this resolved?  If so, can we close?

**Comment by Akshay-Venkatesh** [comment]
Addressed with https://github.com/Akshay-Venkatesh/ucx-py/pull/105
